baseurl: ""
languageCode: en-US
languageLang: en
title: moderndpc.com
pluralizelisttitles: false
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  sitename: moderndpc.com
  copyright: moderndpc.com
  organization: Modern Engineering
  logo: /img/logos/logo_splash_400.png
  intro_video: https://res.cloudinary.com/dceernr67/video/upload/v1719520642/modern-engineering-web/ppvxfcadlupusor1ora7.mp4
  powerBy: powered by [We bring apps](webringapps.com)
  googleVerification:
  googleTrackingId: G-VXPBR64C6K
  maxNews: 5
  social:
    facebook: https://www.facebook.com/profile.php?id=md-modern-engineering
    linkedin: https://www.linkedin.com/in/md-modern-engineering
    instagram: https://www.instagram.com/md-modern-engineering/
  contact:
    base_email: aW5mb0Btb2Rlcm5kcGMuY29tCg==
    base_phone: KzM4NSA5MSA5ODcxOTQyCg==
    address: 295 Madison Avenue, 12th floor, New York, NY 10017
    city: New York, NY

  footer:
    title: Where Modern Design Meets Timeless Engineering
    copyright: M.D. Modern Engineering

menu:
  main:
  - {Name: "Home", Identifier: home, Url: "/", Weight: 10}

  projects:
  - {Name: "Drainage & utilities", Identifier: utilities, Url: "/projects/drainage-and-utilities", Weight: 10}
  - {Name: "Transportation", Identifier: transportation, Url: "/projects/transportation", Weight: 20}
  - {Name: "Aviation", Identifier: aviation, Url: "/projects/aviation", Weight: 30}
  - {Name: "Sustainability", Identifier: sustainability, Url: "/projects/sustainability", Weight: 40}

