backend:
  name: github
  repo: amihalj/mdmodern-v2
  branch: deploy-v2

site_url: https://mdmodern-v2.netlify.app

publish_mode: editorial_workflow
media_folder: static/img/assets
public_folder: /img/assets

slug:
  encoding: "ascii"
  clean_accents: true

collections: # A list of collections the CMS should be able to edit
  - name: projects # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Projects" # Used in the UI
    label_singular: "Project" # Used in the UI, ie: "New Post"
    description: >
      Projects pages
    folder: "content/projects"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    sortable_fields: ['title', 'date', 'listed_intro.order']
    view_filters:
      - label: Posts With Index
        field: title
        pattern: "This is post #"
      - label: Posts Without Index
        field: title
        pattern: front matter post
      - label: Drafts
        field: draft
        pattern: true

    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }
      - { label: "Type", name: "type", widget: "hidden", default: "procedures" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - {
        label: Meta,
        name: meta,
        widget: "object",
        fields: [
          { label: "Title", name: title, widget: string, },
          { label: "Keywords", name: keywords, widget: string, required: false },
          { label: "Description", name: description, widget: string, required: false },
          { label: "Headline", name: headline, widget: string, required: false }
          ]
        }
        
      - label: List view
        name: listed_intro
        widget: "object"
        fields:
          - { label: "Order in group", name: order, widget: number }
          - { label: "Image", name: image, widget: image, class: "thumb" }
          - { label: "Description", name: description, widget: string, required: false }

      - { label: "Heading", name: h1, widget: string }
      - label: Intro images
        name: intro_images
        widget: list
        fields:
        - { label: "Title", name: title, widget: string, required: false }
        - { label: "Tag", name: tag, widget: string, required: false }
        - { label: "Class", name: class, widget: select, options: ["gold", "dark", "gray"] }
        - { label: "Image", name: image, widget: image, class: "thumb" }
      - { label: "Intro", name: intro, widget: markdown, required: false }
      - { label: "Sections title", name: sections_title, widget: string, required: false }
      - label: Sections
        name: sections
        widget: list
        fields:
          - { label: "Title", name: title, widget: string, required: false }
          - { label: "Class", name: class, widget: string, required: false }
          - { label: "Text", name: content, widget: markdown, required: false }
          - label: Section images
            name: images
            widget: list
            required: false
            fields:
            - { label: "Title", name: title, widget: string }
            - { label: "Tag", name: tag, widget: string, required: false }
            - { label: "Class", name: class, widget: select, options: ["gold", "dark", "gray"] }
            - { label: "Image", name: image, widget: image, class: "thumb" }
  
  - name: news # Used in routes, ie.: /admin/collections/:slug/edit
    label: "News" # Used in the UI
    label_singular: "News" # Used in the UI, ie: "New Post"
    description: >
      News pages
    folder: "content/news"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    sortable_fields: ['title', 'date', 'listed_intro.order']
    view_filters:
      - label: Posts With Index
        field: title
        pattern: "This is post #"
      - label: Posts Without Index
        field: title
        pattern: front matter post
      - label: Drafts
        field: draft
        pattern: true

    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }
      - { label: "Type", name: "type", widget: "hidden", default: "procedures" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - {
        label: Meta,
        name: meta,
        widget: "object",
        fields: [
          { label: "Title", name: title, widget: string, },
          { label: "Keywords", name: keywords, widget: string, required: false },
          { label: "Description", name: description, widget: string, required: false },
          { label: "Headline", name: headline, widget: string, required: false }
          ]
        }
        
      - label: List view
        name: listed_intro
        widget: "object"
        fields:
          - { label: "Order in group", name: order, widget: number }
          - { label: "Image", name: image, widget: image, class: "thumb" }
          - { label: "Description", name: description, widget: string, required: false }

      - { label: "Heading", name: h1, widget: string }
      - label: Intro images
        name: intro_images
        widget: list
        fields:
        - { label: "Title", name: title, widget: string }
        - { label: "Tag", name: tag, widget: string, required: false }
        - { label: "Class", name: class, widget: select, options: ["gold", "dark", "gray"] }
        - { label: "Image", name: image, widget: image, class: "thumb" }
      - { label: "Intro", name: intro, widget: markdown, required: false }
      - { label: "Sections title", name: sections_title, widget: string, required: false }
      - label: Sections
        name: sections
        widget: list
        fields:
          - { label: "Title", name: title, widget: string }
          - { label: "Class", name: class, widget: string, required: false }
          - { label: "Text", name: content, widget: markdown, required: false }
          - label: Section images
            name: images
            widget: list
            required: false
            fields:
            - { label: "Title", name: title, widget: string }
            - { label: "Tag", name: tag, widget: string, required: false }
            - { label: "Class", name: class, widget: select, options: ["gold", "dark", "gray"] }
            - { label: "Image", name: image, widget: image, class: "thumb" }
  

  - name: "rest"
    label: "Main pages"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "home"
        label: "Home"
        file: "content/_index.md"
        description: "Home page"
        fields:
          - label: Meta
            name: meta
            widget: "object"
            fields:
              - { label: "Title", name: title, widget: string }
              - { label: "Keywords", name: keywords, widget: string, required: false }
              - { label: "Description", name: description, widget: string, required: false }
              - { label: "Headline", name: headline, widget: string, required: false }
          - { label: "Heading", name: "h1", widget: "string" }
          - label: Accordion section
            name: introduction
            widget: object
            fields:
              - { label: "Title", name: title, widget: string }
              - { label: "Side image", name: side_image, widget: image }
              - label: Items
                name: list
                widget: list
                required: true
                fields:
                - { label: "Title", name: title, widget: string }
                - { label: "Text", name: content, widget: markdown, required: false }
                - label: Actions
                  name: actions
                  widget: list
                  fields:
                    - { label: "Title", name: title, widget: string }
                    - { label: "Link", name: href, widget: string }
          - label: Our team
            name: team
            widget: object
            description: "Team members are set on Team page, only big size members are shown here"
            fields:
              - { label: "Title", name: title, widget: string }
              - { label: "Text", name: content, widget: markdown, required: false }
          - label: Bottom form contact
            name: contact
            widget: object
            fields:
              - { label: "Title", name: title, widget: string }
              - { label: "Text", name: content, widget: markdown, required: false }
      - name: "aboutus"
        label: "About us"
        file: "content/about-us.md"
        description: "About us"
        fields:
          - label: Meta
            name: meta
            widget: "object"
            fields:
              - { label: "Title", name: title, widget: string }
              - { label: "Keywords", name: keywords, widget: string, required: false }
              - { label: "Description", name: description, widget: string, required: false }
              - { label: "Headline", name: headline, widget: string, required: false }
          - { label: "Heading", name: "h1", widget: "string" }
          - { label: "Top image", name: header_image, widget: image, required: false }
          - { label: "Text", name: content, widget: markdown, required: false }
          - { label: "Contact button", name: call_to_action, widget: string }
          - label: Sections
            name: sections
            widget: list
            required: true
            fields:
            - { label: "Title", name: title, widget: string }
            - { label: "Class", name: cls, widget: string, required: false }
            - { label: "Logo", name: logo, widget: image }
            - { label: "Icon", name: icon, widget: string, required: false }
            - { label: "Text", name: content, widget: markdown, required: false }
            - label: Logos
              name: logos
              widget: list
              required: false
              fields:
              - { label: "Title", name: title, widget: string, required: false }
              - { label: "Logo", name: logo, widget: string }


      - name: "services"
        label: "Services"
        file: "content/services.md"
        description: "Services"
        fields:
          - label: Meta
            name: meta
            widget: "object"
            fields:
              - { label: "Title", name: title, widget: string }
              - { label: "Keywords", name: keywords, widget: string, required: false }
              - { label: "Description", name: description, widget: string, required: false }
              - { label: "Headline", name: headline, widget: string, required: false }
          - { label: "Heading", name: "h1", widget: "string" }
          - { label: "Top image", name: header_image, widget: image }
          - { label: "Intro", name: intro, widget: markdown, required: false }
          - { label: "Text", name: content, widget: markdown, required: false }
          - { label: "Contact button", name: call_to_action, widget: string }
          - label: Services
            name: sections
            widget: list
            required: true
            fields:
            - { label: "Title", name: title, widget: string }
            - { label: "Class", name: cls, widget: string, required: false }
            - { label: "Logo", name: logo, widget: image }
            - { label: "Icon", name: icon, widget: string, required: false }
            - { label: "Text", name: content, widget: markdown, required: false }

      - name: "projects"
        label: "Projects"
        file: "content/projects.md"
        description: "Projects"
        fields:
          - label: Meta
            name: meta
            widget: "object"
            fields:
              - { label: "Title", name: title, widget: string }
              - { label: "Keywords", name: keywords, widget: string, required: false }
              - { label: "Description", name: description, widget: string, required: false }
              - { label: "Headline", name: headline, widget: string, required: false }
          - { label: "Heading", name: "h1", widget: "string" }
          - { label: "Top image", name: header_image, widget: image }
          - { label: "Intro", name: intro, widget: markdown, required: false }
          - { label: "Text", name: content, widget: markdown, required: false }
          - label: Projects
            name: sections
            widget: list
            required: true
            fields:
            - { label: "Title", name: title, widget: string }
            - { label: "Text", name: content, widget: markdown, required: false }
            - label: "Tags"
              name: "tags"
              widget: "list"
              field: {label: Tag, name: tag, widget: string}
            - label: Notes
              name: notes
              widget: list
              required: false
              fields:
              - { label: "Title", name: title, widget: string }
              - { label: "Text", name: text, widget: string, required: false }
            - label: Image
              name: image
              widget: "object"
              required: false
              fields:
                - { label: "Image", name: title, widget: image }
                - { label: "Description", name: alt, widget: string, required: false }
            
            - label: Gallery
              name: gallery
              widget: list
              required: false
              fields:
              - { label: "Image", name: src, widget: string }
              - { label: "Description", name: alt, widget: string, required: false }
      - name: "contact"
        label: "Contact"
        file: "content/contact.md"
        description: "Contact page"
        fields:
          - label: Meta
            name: meta
            widget: "object"
            fields:
              - { label: "Title", name: title, widget: string }
              - { label: "Keywords", name: keywords, widget: string, required: false }
              - { label: "Description", name: description, widget: string, required: false }
              - { label: "Headline", name: headline, widget: string, required: false }
          - { label: "Heading", name: "h1", widget: "string" }
          - { label: "Intro", name: intro, widget: markdown, required: false }
          - { label: "Catch phrase", name: catch_phrase, widget: string }
          - label: "Subjects"
            name: "subject"
            widget: "list"
            field: {label: Title, name: title, widget: string}
          - label: Contact form labels
            name: labels
            widget: "object"
            fields:
              - { label: "required", name: required, widget: string, default: "Required fields are marked" }
              - { label: "subject", name: subject, widget: string, default: "Select a subject" }
              - { label: "send", name: send, widget: string, default: "Send Your Message" }
      - name: "team"
        label: "Team"
        file: "content/team.md"
        description: "Team page"
        fields:
          - label: Meta
            name: meta
            widget: "object"
            fields:
              - { label: "Title", name: title, widget: string }
              - { label: "Keywords", name: keywords, widget: string, required: false }
              - { label: "Description", name: description, widget: string, required: false }
              - { label: "Headline", name: headline, widget: string, required: false }
          - { label: "Heading", name: "h1", widget: "string" }
          - { label: "Top image", name: header_image, widget: image }
          - { label: "Intro", name: section_content, widget: markdown, required: false }
          - { label: "Text", name: content, widget: markdown, required: false }
          - { label: "Contact button", name: call_to_action, widget: string }
          - label: Team members
            name: list
            widget: list
            required: true
            fields:
            - { label: "Name", name: name, widget: string }
            - { label: "Title", name: title, widget: string }
            - { label: "Position", name: position, widget: string }
            - { label: "Size", name: size, widget: select, options: ["small", "big"] }
            - { label: "Image", name: img, widget: image }
            - { label: "Text", name: content, widget: markdown, required: false }
          
       
          
